version: "2"

services:
  volcan:
    build: .
    env_file: .env
    environment:
      DB_DSN: postgresql://postgres:postgres@postgres:5432/volcan
      PORT: "8080"
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: volcan
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
